# Generated by Django 6.1.1 on 2026-09-29 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("superficie", models.FloatField()),
                ("consommation_electrique", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.FloatField()),
                ("duree_de_vie", models.FloatField()),
                ("cout_maintenance", models.FloatField()),
                ("superficie", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("tva", models.FloatField()),
                ("tarif_electrique", models.FloatField()),
                ("salaire_minimum", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PrixProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix_achat", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("cout", models.FloatField()),
                ("heures_de_travail", models.IntegerField()),
                ("consommation_electrique", models.FloatField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.machine",
                    ),
                ),
                (
                    "operation_suivante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.operation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointDeVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("heures_de_travail", models.IntegerField()),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.lieu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "prix_produits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.prixproduit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix_de_vente", models.FloatField()),
                ("duree_de_vie", models.IntegerField()),
                ("nombre_par_palette", models.IntegerField()),
                ("operations", models.ManyToManyField(to="high_level.operation")),
            ],
        ),
        migrations.AddField(
            model_name="prixproduit",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.produit"
            ),
        ),
        migrations.CreateModel(
            name="QuantiteMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField()),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.machine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lieu",
            name="quantite_machines",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.quantitemachine",
            ),
        ),
        migrations.CreateModel(
            name="QuantiteProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField()),
                (
                    "matiere_premiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.produit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operation",
            name="quantite_produits",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.quantiteproduit",
            ),
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reduction", models.FloatField()),
                ("client", models.CharField(max_length=100)),
                (
                    "point_de_vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.pointdevente",
                    ),
                ),
                (
                    "quantite_produits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.quantiteproduit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palettes_max", models.IntegerField()),
                (
                    "quantite_produits",
                    models.ManyToManyField(to="high_level.quantiteproduit"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pointdevente",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.stock"
            ),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_palettes", models.IntegerField()),
                ("cout", models.FloatField()),
                ("delai", models.IntegerField()),
                (
                    "arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_arivee",
                        to="high_level.lieu",
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_depart",
                        to="high_level.lieu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("taxe_immobiliere", models.FloatField()),
                ("prix_m2", models.FloatField()),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="high_level.pays",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lieu",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.ville"
            ),
        ),
    ]
