# Generated by Django 6.1.1 on 2026-09-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lieu",
            name="quantite_machines",
        ),
        migrations.AddField(
            model_name="lieu",
            name="quantite_machines",
            field=models.ManyToManyField(to="high_level.quantitemachine"),
        ),
    ]
